### ISSUE TITLE
Any problems forecast building for Xilinx 4.19 kernel (I have a compile error)

### ISSUE THREAD

**Issue by salerio-gs** [logicbricks/driver_fb_logicvc#3]
I tried creating a patch from the contents of the master branch here and applied it to the Xilinx 4.19 kernel (I am using Petalinux 2019.1). When I enabled the misc support in the kernel config I got the following error:

> | /build1/peter/GRAPHICS/ZC702/build/tmp/work-shared/zc702-zynq7/kernel-source/drivers/video/fbdev/xylon/adv7511.c: In function 'adv7511_probe':
> | /build1/peter/GRAPHICS/ZC702/build/tmp/work-shared/zc702-zynq7/kernel-source/drivers/video/fbdev/xylon/adv7511.c:1587:5: warning: "LINUX_VERSION_CODE" is not defined, evaluates to 0 [-Wundef]
> |  #if LINUX_VERSION_CODE <= KERNEL_VERSION(4, 4, 0)
> |      ^~~~~~~~~~~~~~~~~~
> | /build1/peter/GRAPHICS/ZC702/build/tmp/work-shared/zc702-zynq7/kernel-source/drivers/video/fbdev/xylon/adv7511.c:1587:27: warning: "KERNEL_VERSION" is not defined, evaluates to 0 [-Wundef]
> |  #if LINUX_VERSION_CODE <= KERNEL_VERSION(4, 4, 0)
> |                            ^~~~~~~~~~~~~~
> | /build1/peter/GRAPHICS/ZC702/build/tmp/work-shared/zc702-zynq7/kernel-source/drivers/video/fbdev/xylon/adv7511.c:1587:41: error: missing binary operator before token "("
> |  #if LINUX_VERSION_CODE <= KERNEL_VERSION(4, 4, 0)
> |                                          ^
> | make[6]: *** [/build1/peter/GRAPHICS/ZC702/build/tmp/work-shared/zc702-zynq7/kernel-source/scripts/Makefile.build:305: drivers/video/fbdev/xylon/adv7511.o] Error 1

Not being a die hard driver developer I can't tell if this is easily fixed or not. This leads to a further question alluded to in the issue title, do you expect this driver to work with a 4.19 Xilinx kernel.

**Comment by logicbricks** [comment]
Hello salerio-gs,

try adding:

 #include <linux/version.h> 

to the file adv7511.c (/kernel_src/drivers/video/fbdev/xylon/) next to the other #include lines.
The driver is expected to work with the 4.19 Xilinx Kernel.

Best regards,

Xylon Support Team

**Comment by salerio-gs** [comment]
Excellent news, thanks. I'll close this issue.
